package schema

import (
	"reflect"
	"sort"

	"github.com/RubenRibGarcia/asyncgo/spec"
)

// registry maps a fully-qualified type name (pkgPath.TypeName) to its
// reflect.Type. It is populated by generated harness code (Register) and
// consumed by Finalize to hoist the schemas that combinator directives
// reference by name — types reflection cannot reach on its own.
var registry = map[string]reflect.Type{}

// Register records types by fully-qualified name for combinator resolution.
// It is generated by the harness; it is not intended to be called by hand.
// Pointers are dereferenced and anonymous types are ignored. Idempotent.
func Register(types ...any) {
	for _, v := range types {
		t := reflect.TypeOf(v)
		for t.Kind() == reflect.Pointer {
			t = t.Elem()
		}
		if t.Name() == "" || t.PkgPath() == "" {
			continue // anonymous types have no stable FQN
		}
		registry[Name(t)] = t
	}
}

// Finalize hoists every registered type into doc.Components.Schemas so the
// $refs emitted by FromType resolve. Types are derived in sorted-FQN order for
// deterministic output, and existing schemas are never overwritten.
func Finalize(doc *spec.AsyncAPI) {
	if doc == nil {
		return
	}

	names := make([]string, 0, len(registry))
	for name := range registry {
		names = append(names, name)
	}
	sort.Strings(names)

	defs := map[string]*spec.Schema{}
	for _, name := range names {
		FromType(registry[name], defs)
	}
	if len(defs) == 0 {
		return
	}

	if doc.Components == nil {
		doc.Components = &spec.Components{}
	}
	if doc.Components.Schemas == nil {
		doc.Components.Schemas = map[string]*spec.Schema{}
	}
	for name, s := range defs {
		if _, ok := doc.Components.Schemas[name]; !ok {
			doc.Components.Schemas[name] = s
		}
	}
}
